# Generated by Django 5.2.6 on 2025-09-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lesson_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='difficulty_level',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced')], default='1', help_text='The difficulty level of the lesson.', max_length=50),
        ),
    ]
