# Generated by Django 5.2.6 on 2025-09-17 22:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_alter_lesson_difficulty_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontranslation',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='lessontranslation',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio'),
        ),
    ]
