# Generated by Django 5.2.6 on 2025-09-17 23:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_remove_lessontranslation_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontranslation',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Lesson content translation audio', max_length=255, null=True, verbose_name='audio'),
        ),
    ]
